#!/usr/bin/env bash
# D-078: /etc/postfix/sni_map is regenerated by the server's control agent ("do not edit manually"), which
# would drop the mail.mutabe3.news line. Installs a mutabe3-owned guard (systemd path unit on the file +
# hourly timer) that re-adds only our line / Dovecot file when missing and reloads. Touches nothing else.
set -euo pipefail
G=/usr/local/sbin/mutabe3-mail-sni-guard
cat > "$G" <<'EOF'
#!/usr/bin/env bash
# mutabe3 (D-078): keep mail.mutabe3.news in Postfix/Dovecot SNI. Only ever adds our own entries.
H=mail.mutabe3.news; LE=/etc/letsencrypt/live/$H; SNI=/etc/postfix/sni_map; D=/etc/dovecot/conf.d/sni/$H.conf
[ -s "$LE/fullchain.pem" ] || exit 0
if ! grep -qE "^$H[[:space:]]" "$SNI" 2>/dev/null; then
  printf '%s %s %s\n' "$H" "$LE/privkey.pem" "$LE/fullchain.pem" >> "$SNI" && postfix reload >/dev/null 2>&1
  logger -t mutabe3-mail-sni-guard "re-added $H to $SNI"
fi
if [ ! -f "$D" ] && [ -d "$(dirname "$D")" ]; then
  printf '# mutabe3 (D-078)\nlocal_name %s {\n  ssl_cert = <%s/fullchain.pem\n  ssl_key = <%s/privkey.pem\n}\n' "$H" "$LE" "$LE" > "$D"
  doveconf -n >/dev/null 2>&1 && systemctl reload dovecot || rm -f "$D"
  logger -t mutabe3-mail-sni-guard "re-added $D"
fi
EOF
chmod 755 "$G"
cat > /etc/systemd/system/mutabe3-mail-sni-guard.service <<EOF
[Unit]
Description=mutabe3: keep mail.mutabe3.news in Postfix/Dovecot SNI (D-078)
[Service]
Type=oneshot
ExecStart=$G
EOF
cat > /etc/systemd/system/mutabe3-mail-sni-guard.path <<'EOF'
[Unit]
Description=mutabe3: watch Postfix SNI map (D-078)
[Path]
PathChanged=/etc/postfix/sni_map
PathChanged=/etc/dovecot/conf.d/sni
[Install]
WantedBy=multi-user.target
EOF
cat > /etc/systemd/system/mutabe3-mail-sni-guard.timer <<'EOF'
[Unit]
Description=mutabe3: hourly SNI check (D-078)
[Timer]
OnBootSec=2min
OnUnitActiveSec=1h
[Install]
WantedBy=timers.target
EOF
systemctl daemon-reload
systemctl enable --now mutabe3-mail-sni-guard.path mutabe3-mail-sni-guard.timer
systemctl is-active mutabe3-mail-sni-guard.path mutabe3-mail-sni-guard.timer
echo "== self-test: remove our line, expect the guard to restore it =="
cp -p /etc/postfix/sni_map /root/mail-dns-backup/sni_map.guardtest.$(date -u +%s)
sed -i '/^mail\.mutabe3\.news[[:space:]]/d' /etc/postfix/sni_map
sleep 4
grep -c '^mail\.mutabe3\.news' /etc/postfix/sni_map | sed 's/^/our lines after guard: /'
journalctl -t mutabe3-mail-sni-guard --since '-1min' --no-pager -o cat | tail -2
echo | timeout 10 openssl s_client -starttls smtp -connect 127.0.0.1:25 -servername mail.mutabe3.news -verify_hostname mail.mutabe3.news 2>/dev/null | grep 'Verify return code'
